runtime: go115
service: simple-webapp-sql

env_variables:
  PORT: 8080
  INSTANCE_CONNECTION_NAME: test1-cc:europe-west1:db-webapp
  DB_USER: test
#  DB_PASS: cloud*******2021 (stored in secret)
  DB_NAME: webapp