runtime: go115
service: simple-webapp-sql

env_variables:
  PORT: 8080
  INSTANCE_CONNECTION_NAME: webapp-shop-303617:europe-west1:db-webapp
  DB_USER: test
#  DB_PASS: cloud*******2021 (stored in secret)
  DB_NAME: webapp
  OAUTH_REDIRECT_URL: https://simple-webapp-nosql-dot-webapp-shop-303617.ew.r.appspot.com/callback

handlers:
  - url: /.*
    script: auto
    secure: always

error_handlers:
  - file: /static/default_error.html
