steps:
  - id: 'pull dependencies'
    name: 'golang'
    args: [ 'go', 'build', '.' ]
    env: [ 'GO111MODULE=on' ]

  - id: 'deploy app'
    name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"