steps:
  - id: 'Pull dependencies'
    name: 'golang'
    args: [ 'go', 'build', '.' ]
    env: [ 'GO111MODULE=on' ]

  - id: 'Test'
    name: "gcr.io/cloud-builders/go"
    args: ["test", "simple-webapp-go"]

  - id: 'Deploy App'
    name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]

timeout: "1600s"